### ISSUE TITLE
Score Reporting for Matches

### ISSUE THREAD

**Issue by shawnd** [x3igh7/ftwgl#45]
<h1> Score Submission:

<h2> Map1 ie ut4_turnpike
- input your-clan-name
- input other-clan-name

<h2> Map2 ie ut4_tohunga_b8
- input your-clan-name
- input other-clan-name

<h2> Media Upload
- Upload screenshots/urtdemo files

<h2> Players
- List of all players on your clans roster, with radio boxes yes and no to indicate whether or not the player played in the match.

button submit scores

_For CTF, instead of Map1 and Map2 it would be Red Side / Blue Side_

_If score submissions match, display immediately. If the submissions from both teams do not match, have admin review_

**Comment by x3igh7** [comment]
partially completed
